### ISSUE TITLE
Blink1 not recognized

### ISSUE THREAD

**Issue by JeffreyDavidsz** [bitfocus/companion-module-thingm-blink1#1]
Module does not show the blink1 (Facebook post)

**Comment by JeffreyDavidsz** [comment]
Need to check this against the new version

**Comment by haakonnessjoen** [comment]
Yes, please retest with current developer release of companion.

**Comment by JeffreyDavidsz** [comment]
Ok, on version 2.0 (OSX) the Blink1 does work. It is seen by companion as local

**Comment by JeffreyDavidsz** [comment]
In version 1.3 (from Beta folder) it is not seen
