### ISSUE TITLE
Javascript error uncaught exception when trying to edit blink(1) instance in companion

### ISSUE THREAD

**Issue by ibinbin** [bitfocus/companion-module-thingm-blink1#4]
**Describe the bug**
Got error windows from companion when I try to edit config of Blink(1) MK3 in admin interface

**To Reproduce**

1. plug Blink(1)
2. open blink control 2 version 2.2.4
3. open companion version 2.1.3
4. add blink(1) instance
5. try to edit it

**Expected behavior**
should open the configu tab for selecting the device to use

**Screenshots**
![Capture](https://user-images.githubusercontent.com/479261/131184007-92910db8-5e08-4e01-8825-d99de2b3bd10.PNG)
![Captures](https://user-images.githubusercontent.com/479261/131184392-b65239d9-3bf9-45bb-b73a-9a3e3881b36a.PNG)

**Desktop (please complete the following information):**
- OS: Win10
- Browser chrome
- Companion Version 2.1.3

**Comment by Julusian** [comment]
I am pretty sure this was fixed in 2.2/2.3. It is definitely fine as of 3.0
